CREATE DATABASE universityDB; 
USE universityDB; 
CREATE TABLE STUDENT (
	STDNO				CHAR(11)		NOT NULL, 
    STDFIRSTNAME		VARCHAR(30)		NOT NULL,
    STDLASTNAME			VARCHAR(30)		NOT NULL, 
    STDCITY				VARCHAR(30)		NOT NULL, 
    STDSTATE			CHAR(2)			NOT NULL,
    STDZIP 				CHAR(10)		NOT NULL, 
    STDMAJOR			CHAR(6),
    STDCLASS			CHAR(2),
    STDGPA				DECIMAL(3,2),
    
    CONSTRAINT STUDENT_PK PRIMARY KEY(STDNO)
);
