CREATE TABLE CUSTOMER (
	CUSTNO 			VARCHAR(8)		NOT NULL, 
    CUSTNAME		VARCHAR(20)		NOT NULL, 
    ADDRESS 		VARCHAR(20)		NOT NULL, 
    INTERNAL 		CHAR(1)			NOT NULL, 
    CONTACT			VARCHAR(20)		NOT NULL, 
    PHONE 			NUMERIC(10)		NOT NULL,
    CITY 			VARCHAR(10)		NOT NULL, 
    STATE 			CHAR(2)			NOT NULL, 
    ZIP 			NUMERIC(10)		NOT NULL,
    
    CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTNO) 
);
