CREATE TABLE EMPLOYEE (
	  EMPNO 		  VARCHAR(8)		NOT NULL, 
    EMPNAME		  VARCHAR(20) 	NOT NULL,  
    DEPARTMENT	VARCHAR(20)		NOT NULL, 
    EMAIL 		  VARCHAR(20)		NOT NULL	UNIQUE, 
    PHONE 		  NUMERIC(20)		NOT NULL, 
    
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY(EMPNO)
);
