
CREATE TABLE EVENTREQUEST (
	  EVENTNO 		  VARCHAR(8)		NOT NULL, 
    DATEHELD		  DATE			    NOT NULL, 
    DATEREQ 		  DATE 			    NOT NULL, 
    CUSTNO			  VARCHAR(8)		NOT NULL, 
    FACNO			    VARCHAR(10)		NOT NULL, 
    DATEAUTH		  DATE,
    STATUS			  VARCHAR(20)		NOT NULL, 
    ESTCOST			  DECIMAL(6,2)	NOT NULL,
    ESTAUDIENCE		NUMERIC(10)		NOT NULL, 
    BUDNO			    VARCHAR(10),
    
    CONSTRAINT EVENTREQUEST_PK PRIMARY KEY(EVENTNO),
    CONSTRAINT CUSTOMER_FK FOREIGN KEY(CUSTNO) REFERENCES CUSTOMER(CUSTNO),
    CONSTRAINT FACILITY_FK FOREIGN KEY(FACNO) REFERENCES FACILITY(FACNO), 
    
    CHECK (ESTAUDIENCE > 0),
    CHECK(STATUS IN ("Pending", "Approved", "Denied"))
);
