
CREATE TABLE EVENTPLANLINE(
	  PLANNO 		  VARCHAR(8)		NOT NULL, 
    LINENO		  NUMERIC(10)		NOT NULL, 
    TIMESTART 	time			NOT NULL,
    TIMEEND		  TIME 			NOT NULL, 
    NUMBERFLD 	NUMERIC(10)		NOT NULL, 
    LOCNO 		  VARCHAR(8)		NOT NULL, 
    RESNO 		  VARCHAR(8)		NOT NULL, 
    
    CONSTRAINT EVENTPLANLINE_PK PRIMARY KEY(PLANNO), 
    CONSTRAINT EVENTPLAN_FK FOREIGN KEY(PLANNO) REFERENCES EVENTPLAN(PLANNO), 
    CONSTRAINT LOCATION_FK 	FOREIGN KEY(LOCNO) REFERENCES LOCATION(LOCNO), 
    CONSTRAINT RESOURCETBL_FK FOREIGN KEY(RESNO) REFERENCES RESOURCETBL(RESNO),
    CHECK(TIMESTART < TIMEEND)
);

