CREATE TABLE EVENTPLAN(
	  PLANNO 		VARCHAR(8)		NOT NULL, 
    EVENTNO 	VARCHAR(20)		NOT NULL, 
    WORKDATE 	DATE			    NOT NULL, 
    NOTES		  VARCHAR(20), 
    ACTIVITY 	VARCHAR(20)		NOT NULL, 
    EMPNO		  VARCHAR(10),
    
    CONSTRAINT 	EVENTPLAN_PK PRIMARY KEY(PLANNO), 
    CONSTRAINT 	EVENTREQUEST_FK FOREIGN KEY(EVENTNO) REFERENCES EVENTREQUEST(EVENTNO), 
    CONSTRAINT 	EMPLOYEE_FK FOREIGN KEY(EMPNO) REFERENCES EMPLOYEE(EMPNO)
);
