INSERT INTO FACILITY VALUES('F100', "Football stadium");
INSERT INTO FACILITY VALUES('F101', "Basketball arena");
INSERT INTO FACILITY VALUES('F102', "Baseball field");
INSERT INTO FACILITY VALUES('F103', "Recreation room");
